### ISSUE TITLE
No fading down with ppsspp

### ISSUE THREAD

**Issue by kirk899** [Rydra/bgm-for-es#7]
With Retropie and the script Rydra/bgm-for-es is not Fading down the music, when i start the Emulator ppsspp.

I think it´s a bug. It´s okay with the other Emulators but not with ppsspp

BR

**Comment by Rydra** [comment]
I have bumped to the new version of the Background music for EmulationStation. This new release is a complete revamp, with a new installation script. Please follow the following steps:
1. Uninstall the old script if you had it:
```
sudo apt remove python-es-bgm
```
2. Go to the main page of the project and reinstall the script, following the instructions of the documentation:

```
https://github.com/Rydra/bgm-for-es
```
The new config file will allow you to set the ppsspp process so that the music stops for that specific emulator. Feedback always appreciated!
